---
- name: Install and Start Nginx on Localhost
  hosts: webservers
  become: true

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

